In [1]:
#importing essential libraries

import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

In [2]:
#loading the training data into a dataframe

data = pd.read_csv("https://raw.githubusercontent.com/vrindamathur1428/DataSets/master/TimeForecasting_train.csv")
data.head()

   id                 time   feature_1     feature_2
0   0  2019-03-19 00:00:00  735.740043  54479.540513
1   1  2019-03-19 00:00:10  734.102947  47888.033714
2   2  2019-03-19 00:00:20  730.060336  47700.882325
3   3  2019-03-19 00:00:30  725.609742  47790.094648
4   4  2019-03-19 00:00:40  724.328480  47808.402381

In [3]:
#here we can see the data types of all columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         564 non-null    int64
 1   time       564 non-null    object
 2   feature_1  564 non-null    float64
 3   feature_2  564 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 17.8+ KB

In [4]:
#modifying the data such that the datatype of "time" column is changed from string object to date-time object
#this will help in making calculations easier

dateparse = lambda dates: pd.datetime.strptime(dates, "%Y-%m-%d %H:%M:%S")
data = pd.read_csv("https://raw.githubusercontent.com/vrindamathur1428/DataSets/master/TimeForecasting_train.csv", parse_dates=['time'], date_parser=dateparse)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  after removing the cwd from sys.path.

In [5]:
#converting the date-time object into float object
#because random forest regressor takes only float variables as input(and not categorical)

def datetime_to_float(d):
    return d.timestamp()

for i in range(len(data["time"])):
    data.loc[i, "time"]=datetime_to_float(data.loc[i, "time"])

In [6]:
#this is what modified data looks like

data.head()

   id         time   feature_1     feature_2
0   0  1.55295e+09  735.740043  54479.540513
1   1  1.55295e+09  734.102947  47888.033714
2   2  1.55295e+09  730.060336  47700.882325
3   3  1.55295e+09  725.609742  47790.094648
4   4  1.55295e+09  724.328480  47808.402381

In [7]:
#here we can see that the data type of "time" column is changed

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         564 non-null    int64
 1   time       564 non-null    object
 2   feature_1  564 non-null    float64
 3   feature_2  564 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 17.8+ KB

In [8]:
#separating the data into features(variables) and labels(targets)

x=data.loc[:, ["time", "feature_1"]] #featuers
y=data["feature_2"] #labels

In [9]:
#Standardizing the training data: Scale the data to be between -1 and 1
scaler = StandardScaler()
scaler.fit(x)
x= scaler.transform(x)

In [10]:
#creating an object of random forest regression model and training it on training data
regressor = RandomForestRegressor(n_estimators = 50, max_depth=20, random_state = 0) 
X=np.array(x)
Y=np.array(y)
regressor.fit(X, Y)

RandomForestRegressor(max_depth=20, n_estimators=50, random_state=0)

In [11]:
#loading test data into a new dataframe

testData=pd.read_csv("https://raw.githubusercontent.com/vrindamathur1428/DataSets/master/TimeForecasting_test.csv")
testData.head()

    id                 time   feature_1
0  564  2019-03-19 01:34:00  423.064004
1  565  2019-03-19 01:34:10  423.342749
2  566  2019-03-19 01:34:20  423.181186
3  567  2019-03-19 01:34:30  421.275243
4  568  2019-03-19 01:34:40  422.208444

In [12]:
#modifying the test data like we did the training data

dateparse = lambda dates: pd.datetime.strptime(dates, "%Y-%m-%d %H:%M:%S")
testData = pd.read_csv("https://raw.githubusercontent.com/vrindamathur1428/DataSets/master/TimeForecasting_test.csv", parse_dates=['time'], date_parser=dateparse)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  This is separate from the ipykernel package so we can avoid doing imports until

In [13]:
for i in range(len(testData["time"])):
    testData.loc[i, "time"]=datetime_to_float(testData.loc[i, "time"])

In [14]:
testData.head()

    id         time   feature_1
0  564  1.55296e+09  423.064004
1  565  1.55296e+09  423.342749
2  566  1.55296e+09  423.181186
3  567  1.55296e+09  421.275243
4  568  1.55296e+09  422.208444

In [15]:
#storing the feature vectors in "x_test" variable
x_test=testData.loc[:, ["time", "feature_1"]]

#variable "id" will store the corresponding ids to assign to the predicted output
ids=testData["id"]

In [16]:
#the same scaling and shifting operations will be applied to the test data to be consistent with the transformation performed on the train data:
x_test= scaler.transform(x_test)

In [17]:
#this is what scaled test data looks like
x_test

array([[ 1.73512455, -1.42935774],
       [ 1.74126658, -1.42540081],
       [ 1.74740861, -1.42769428],
       [ 1.75355065, -1.4547501 ],
       [ 1.75969268, -1.44150284],
       [ 1.76583472, -1.43571377],
       [ 1.77197675, -1.39009635],
       [ 1.77811878, -1.38421851],
       [ 1.78426082, -1.38707477],
       [ 1.79040285, -1.40566386],
       [ 1.79654488, -1.4059969 ],
       [ 1.80268692, -1.54630962],
       [ 1.80882895, -1.41759013],
       [ 1.81497099, -1.4293247 ],
       [ 1.82111302, -1.43289807],
       [ 1.82725505, -1.43571004],
       [ 1.83339709, -1.43992626],
       [ 1.83953912, -1.44644915],
       [ 1.84568116, -1.45513535],
       [ 1.85182319, -1.67915983],
       [ 1.85796522, -1.47647258],
       [ 1.86410726, -1.46230474],
       [ 1.87024929, -1.46568713],
       [ 1.87639132, -1.48022847],
       [ 1.88253336, -1.48502637],
       [ 1.88867539, -1.49094817],
       [ 1.89481743, -1.49813917],
       [ 1.90095946, -1.50314876],
       [ 1.90710149, -1.51074547],
       [ 1.91324353, -1.50995788],
       [ 1.91938556, -1.51824885],
       [ 1.92552759, -1.51396712],
       [ 1.93166963, -1.51773395],
       [ 1.93781166, -1.53770062],
       [ 1.9439537 , -1.52976124],
       [ 1.95009573, -1.52135316],
       [ 1.95623776, -1.54499627],
       [ 1.9623798 , -1.55145268],
       [ 1.96852183, -1.56366513],
       [ 1.97466386, -1.55857261],
       [ 1.9808059 , -1.56048239],
       [ 1.98694793, -1.56491383],
       [ 1.99308997, -1.56574931],
       [ 1.999232  , -1.55382412],
       [ 2.00537403, -1.58485223],
       [ 2.01151607, -1.58862562],
       [ 2.0176581 , -1.58198122],
       [ 2.02380014, -1.59533454],
       [ 2.02994217, -1.58794951],
       [ 2.0360842 , -1.59360455],
       [ 2.04222624, -1.60380581],
       [ 2.04836827, -1.6109958 ],
       [ 2.0545103 , -1.60462226],
       [ 2.06065234, -1.60411957],
       [ 2.06679437, -1.71843135],
       [ 2.07293641, -1.7003557 ],
       [ 2.07907844, -1.61754019],
       [ 2.08522047, -1.61946324],
       [ 2.09136251, -1.63301937],
       [ 2.09750454, -1.62801858],
       [ 2.10364657, -1.63819407],
       [ 2.10978861, -1.64782274],
       [ 2.11593064, -1.63953473],
       [ 2.12207268, -1.67058592],
       [ 2.12821471, -1.76914108],
       [ 2.13435674, -1.67217082],
       [ 2.14049878, -1.67210616],
       [ 2.14664081, -1.66861823],
       [ 2.15278285, -1.67322844],
       [ 2.15892488, -1.67034182],
       [ 2.16506691, -1.66614952],
       [ 2.17120895, -1.67796882],
       [ 2.17735098, -1.69531032],
       [ 2.18349301, -1.69733479],
       [ 2.18963505, -1.69532581],
       [ 2.19577708, -1.69475358],
       [ 2.20191912, -1.69451565],
       [ 2.20806115, -1.76088243],
       [ 2.21420318, -1.70766456],
       [ 2.22034522, -1.71492685],
       [ 2.22648725, -1.71576793],
       [ 2.23262928, -1.7154025 ],
       [ 2.23877132, -1.73607217],
       [ 2.24491335, -1.73477435],
       [ 2.25105539, -1.73283073],
       [ 2.25719742, -1.73762515],
       [ 2.26333945, -1.73728102],
       [ 2.26948149, -1.74015888],
       [ 2.27562352, -1.74130199],
       [ 2.28176555, -1.75893571],
       [ 2.28790759, -1.76816516],
       [ 2.29404962, -1.82753594],
       [ 2.30019166, -1.78106878],
       [ 2.30633369, -1.77874078],
       [ 2.31247572, -1.78044662],
       [ 2.31861776, -1.78301768],
       [ 2.32475979, -1.80727799],
       [ 2.33090183, -1.80193299],
       [ 2.33704386, -1.80449917],
       [ 2.34318589, -1.82064218],
       [ 2.34932793, -1.81027688],
       [ 2.35546996, -1.8230666 ],
       [ 2.36161199, -1.89681735],
       [ 2.36775403, -1.82044276],
       [ 2.37389606, -1.81871759],
       [ 2.3800381 , -1.83348315],
       [ 2.38618013, -1.83335382],
       [ 2.39232216, -1.82159611],
       [ 2.3984642 , -1.82689193],
       [ 2.40460623, -1.89347645],
       [ 2.41074826, -1.90871236],
       [ 2.4168903 , -1.83680442],
       [ 2.42303233, -1.84631098],
       [ 2.42917437, -1.84738947],
       [ 2.4353164 , -1.846303  ],
       [ 2.44145843, -1.84939071],
       [ 2.44760047, -1.871752  ],
       [ 2.4537425 , -1.87026549],
       [ 2.45988453, -1.91145012],
       [ 2.46602657, -1.8775974 ],
       [ 2.4721686 , -1.8768491 ],
       [ 2.47831064, -1.88891959],
       [ 2.48445267, -1.89210563],
       [ 2.4905947 , -1.88953022],
       [ 2.49673674, -1.90223192],
       [ 2.50287877, -1.96422156],
       [ 2.50902081, -1.91321557],
       [ 2.51516284, -1.91186556],
       [ 2.52130487, -1.91253983],
       [ 2.52744691, -1.91263972],
       [ 2.53358894, -1.91329748],
       [ 2.53973097, -1.92320207],
       [ 2.54587301, -1.92179107],
       [ 2.55201504, -1.91333241],
       [ 2.55815708, -1.92063303],
       [ 2.56429911, -1.92402917],
       [ 2.57044114, -1.92990614],
       [ 2.57658318, -1.92861432],
       [ 2.58272521, -1.94184286],
       [ 2.58886724, -1.99219753],
       [ 2.59500928, -1.94013947],
       [ 2.60115131, -1.93834673],
       [ 2.60729335, -2.00066615],
       [ 2.61343538, -1.94669387],
       [ 2.61957741, -1.94434926],
       [ 2.62571945, -1.9588812 ],
       [ 2.63186148, -1.95600495],
       [ 2.63800351, -1.95500671],
       [ 2.64414555, -1.96548025],
       [ 2.65028758, -1.97108584],
       [ 2.65642962, -1.97061311],
       [ 2.66257165, -1.97508251],
       [ 2.66871368, -1.98269676],
       [ 2.67485572, -1.98589681],
       [ 2.68099775, -1.98713646],
       [ 2.68713979, -1.99439549],
       [ 2.69328182, -1.99620718],
       [ 2.69942385, -1.98912462],
       [ 2.70556589, -1.99494711],
       [ 2.71170792, -2.09285761],
       [ 2.71784995, -2.02543765],
       [ 2.72399199, -2.02650995],
       [ 2.73013402, -2.03487309],
       [ 2.73627606, -2.03205744],
       [ 2.74241809, -2.03468886],
       [ 2.74856012, -2.02865372],
       [ 2.75470216, -2.03371485],
       [ 2.76084419, -2.04424643],
       [ 2.76698622, -2.04319229],
       [ 2.77312826, -2.05178622],
       [ 2.77927029, -2.26716054],
       [ 2.78541233, -2.04489649],
       [ 2.79155436, -2.04291238],
       [ 2.79769639, -2.05053035],
       [ 2.80383843, -2.05999708],
       [ 2.80998046, -2.05179175],
       [ 2.81612249, -2.0428701 ],
       [ 2.82226453, -2.04569953],
       [ 2.82840656, -2.05217345],
       [ 2.8345486 , -2.06709678],
       [ 2.84069063, -2.07904363],
       [ 2.84683266, -2.07111814],
       [ 2.8529747 , -2.06370446],
       [ 2.85911673, -2.06989076],
       [ 2.86525877, -2.07543207],
       [ 2.8714008 , -2.08000458],
       [ 2.87754283, -2.08647545],
       [ 2.88368487, -2.08486497],
       [ 2.8898269 , -2.08762356],
       [ 2.89596893, -2.08702628],
       [ 2.90211097, -2.09355386],
       [ 2.908253  , -2.09800777],
       [ 2.91439504, -2.09133436],
       [ 2.92053707, -2.0971097 ],
       [ 2.9266791 , -2.10505605],
       [ 2.93282114, -2.11118709],
       [ 2.93896317, -2.15119589],
       [ 2.9451052 , -2.15592784],
       [ 2.95124724, -2.09377667],
       [ 2.95738927, -2.07955218],
       [ 2.96353131, -2.08817339],
       [ 2.96967334, -2.0864704 ],
       [ 2.97581537, -2.08778628],
       [ 2.98195741, -2.09922077],
       [ 2.98809944, -2.09537946],
       [ 2.99424147, -2.08419068],
       [ 3.00038351, -2.08152313],
       [ 3.00652554, -2.16708698],
       [ 3.01266758, -2.1636684 ],
       [ 3.01880961, -2.10698791],
       [ 3.02495164, -2.10297189],
       [ 3.03109368, -2.11270835],
       [ 3.03723571, -2.11398942],
       [ 3.04337775, -2.12372838],
       [ 3.04951978, -2.10787608],
       [ 3.05566181, -2.09363464],
       [ 3.06180385, -2.10139927],
       [ 3.06794588, -2.08516736],
       [ 3.07408791, -2.04577056],
       [ 3.08022995, -2.02807872],
       [ 3.08637198, -2.03484915],
       [ 3.09251402, -2.04867856],
       [ 3.09865605, -2.04816791],
       [ 3.10479808, -2.05233207],
       [ 3.11094012, -2.02399909],
       [ 3.11708215, -2.03144813],
       [ 3.12322418, -2.05291317],
       [ 3.12936622, -2.03370548],
       [ 3.13550825, -2.03527107],
       [ 3.14165029, -2.0306121 ],
       [ 3.14779232, -2.04883489],
       [ 3.15393435, -2.05583341],
       [ 3.16007639, -2.05748998],
       [ 3.16621842, -2.06776375],
       [ 3.17236045, -2.07421272],
       [ 3.17850249, -2.08812272],
       [ 3.18464452, -2.1009751 ],
       [ 3.19078656, -2.10548444],
       [ 3.19692859, -2.11234819],
       [ 3.20307062, -2.12151155],
       [ 3.20921266, -2.11681201],
       [ 3.21535469, -2.13055771],
       [ 3.22149673, -2.25543835],
       [ 3.22763876, -2.1316966 ],
       [ 3.23378079, -2.13829336],
       [ 3.23992283, -2.12839505],
       [ 3.24606486, -2.06769817],
       [ 3.25220689, -1.92735694],
       [ 3.25834893, -1.87646488],
       [ 3.26449096, -1.80971148],
       [ 3.270633  , -1.79452455],
       [ 3.27677503, -1.76321056],
       [ 3.28291706, -1.77044727],
       [ 3.2890591 , -1.73562803],
       [ 3.29520113, -1.75139159],
       [ 3.30134316, -1.81504892],
       [ 3.3074852 , -1.77625678],
       [ 3.31362723, -1.76496541],
       [ 3.31976927, -1.74957026],
       [ 3.3259113 , -1.75134713],
       [ 3.33205333, -1.79183395],
       [ 3.33819537, -1.75619037],
       [ 3.3443374 , -1.77342723],
       [ 3.35047944, -1.77508374],
       [ 3.35662147, -1.78924737],
       [ 3.3627635 , -1.78241379],
       [ 3.36890554, -1.78977418],
       [ 3.37504757, -1.79896303],
       [ 3.3811896 , -1.79286361],
       [ 3.38733164, -1.76146432],
       [ 3.39347367, -1.68166658],
       [ 3.39961571, -1.59795499],
       [ 3.40575774, -1.55919803],
       [ 3.41189977, -1.47802314],
       [ 3.41804181, -1.37285178],
       [ 3.42418384, -1.30765871],
       [ 3.43032587, -1.28683159],
       [ 3.43646791, -1.28607787],
       [ 3.44260994, -1.3868084 ],
       [ 3.44875198, -1.4178095 ],
       [ 3.45489401, -1.18340669],
       [ 3.46103604, -1.04977751],
       [ 3.46717808, -0.95039656],
       [ 3.47332011, -0.9098953 ],
       [ 3.47946214, -0.90231118],
       [ 3.48560418, -0.90370649],
       [ 3.49174621, -0.88441759],
       [ 3.49788825, -0.85588959],
       [ 3.50403028, -0.85108844],
       [ 3.51017231, -0.85233554],
       [ 3.51631435, -0.86617582],
       [ 3.52245638, -0.85449446],
       [ 3.52859842, -0.8539153 ],
       [ 3.53474045, -0.84560101],
       [ 3.54088248, -0.84851402],
       [ 3.54702452, -0.80718852],
       [ 3.55316655, -0.81091785],
       [ 3.55930858, -0.84777276],
       [ 3.56545062, -0.85823122],
       [ 3.57159265, -0.86718661],
       [ 3.57773469, -0.87938737],
       [ 3.58387672, -0.90974846],
       [ 3.59001875, -0.92656795],
       [ 3.59616079, -0.93545077],
       [ 3.60230282, -0.95369526],
       [ 3.60844485, -0.97350304],
       [ 3.61458689, -1.0024066 ],
       [ 3.62072892, -1.02685875],
       [ 3.62687096, -1.05737628],
       [ 3.63301299, -1.05720859],
       [ 3.63915502, -1.07185552],
       [ 3.64529706, -1.07481437],
       [ 3.65143909, -1.10877742],
       [ 3.65758112, -1.11460458],
       [ 3.66372316, -1.12552505],
       [ 3.66986519, -1.11218121],
       [ 3.67600723, -1.08485738],
       [ 3.68214926, -1.06865758],
       [ 3.68829129, -0.97873088],
       [ 3.69443333, -0.87796831],
       [ 3.70057536, -0.84391369],
       [ 3.7067174 , -0.83522462],
       [ 3.71285943, -0.83382953],
       [ 3.71900146, -0.84023801],
       [ 3.7251435 , -0.84597228],
       [ 3.73128553, -0.85747099],
       [ 3.73742756, -0.85968756],
       [ 3.7435696 , -0.89745713],
       [ 3.74971163, -0.93538481],
       [ 3.75585367, -0.88096385],
       [ 3.7619957 , -0.89415947],
       [ 3.76813773, -0.89718333],
       [ 3.77427977, -0.9062875 ],
       [ 3.7804218 , -0.92837781],
       [ 3.78656383, -0.94669391],
       [ 3.79270587, -0.9509557 ],
       [ 3.7988479 , -0.96584051],
       [ 3.80498994, -0.97836391],
       [ 3.81113197, -0.99660369],
       [ 3.817274  , -1.00086816],
       [ 3.82341604, -1.02543517],
       [ 3.82955807, -1.11304839],
       [ 3.8357001 , -1.03814534],
       [ 3.84184214, -1.04358156],
       [ 3.84798417, -1.04082735],
       [ 3.85412621, -1.0540821 ],
       [ 3.86026824, -1.06751535],
       [ 3.86641027, -1.06903232],
       [ 3.87255231, -1.08673641],
       [ 3.87869434, -1.11052392],
       [ 3.88483638, -1.11240889],
       [ 3.89097841, -1.12101176],
       [ 3.89712044, -1.13213012],
       [ 3.90326248, -1.15127568],
       [ 3.90940451, -1.16271647],
       [ 3.91554654, -1.16753836],
       [ 3.92168858, -1.18951133],
       [ 3.92783061, -1.19810071],
       [ 3.93397265, -1.21635517],
       [ 3.94011468, -1.23595224],
       [ 3.94625671, -1.24074529],
       [ 3.95239875, -1.24536892],
       [ 3.95854078, -1.25979937],
       [ 3.96468281, -1.26039713],
       [ 3.97082485, -1.26651632],
       [ 3.97696688, -1.27905221],
       [ 3.98310892, -1.28246432],
       [ 3.98925095, -1.29298359],
       [ 3.99539298, -1.30408296],
       [ 4.00153502, -1.29876849],
       [ 4.00767705, -1.29835881],
       [ 4.01381908, -1.27892418],
       [ 4.01996112, -1.25017606],
       [ 4.02610315, -1.12384898],
       [ 4.03224519, -1.03511438]])

In [18]:
#predicting the "feature_2" value using the Random forest regression model created above

X_test=np.array(x_test)
y_pred = regressor.predict(X_test)

In [19]:
#predicted values

y_pred

array([53930.97907935, 53930.97907935, 53930.97907935, 53936.36678153,
       53936.36678153, 53931.1228025 , 53952.44998984, 53946.96792919,
       53946.96792919, 53954.10705564, 53954.10705564, 53940.28063127,
       53951.86745693, 53930.97907935, 53931.1228025 , 53931.1228025 ,
       53931.1228025 , 53936.36678153, 53936.36678153, 53940.28063127,
       53940.28063127, 53936.36678153, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53940.28063127, 53940.28063127,
       53940.28063127, 53940.28063127, 53947.98222157, 53977.40537691,
       53977.60466144, 53976.95414898, 53946.96792919, 53951.86745693,
       53843.82593907, 53745.98707563, 53750.54715526, 53750.54715526,
       53750.54715526, 53750.54715526, 53750.54715526, 53734.69794869,
       53734.69794869, 53734.69794869, 53750.54715526, 53734.69794869,
       53734.69794869, 53734.77122548, 53734.69794869, 53734.77122548,
       53734.77122548, 53734.69794869, 53734.69794869, 53750.54715526,
       53750.54715526, 53750.54715526, 53750.54715526, 53750.54715526,
       53750.54715526, 53750.54715526, 53751.45582241, 53741.81593744,
       53755.17989902, 53755.17989902, 53781.7030902 , 53811.38595776,
       53844.37135651, 53844.37135651, 53844.37135651, 53844.37135651,
       53844.37135651, 53781.7030902 , 53750.54715526, 53750.54715526,
       53734.77122548, 53734.77122548, 53734.77122548, 53734.77122548,
       53734.77122548, 53734.69794869, 53734.69794869, 53750.54715526,
       53750.54715526, 53750.54715526, 53750.54715526, 53750.54715526,
       53750.54715526, 53750.54715526, 53750.54715526, 53750.54715526,
       53750.54715526, 53750.54715526, 53750.54715526, 53750.54715526,
       53741.81593744, 53844.37135651, 53745.98707563, 53745.98707563,
       53745.98707563, 53742.30813744, 53787.54812171, 53781.7030902 ,
       53844.37135651, 53844.37135651, 53844.37135651, 53844.37135651,
       53844.37135651, 53844.37135651, 53844.37135651, 53844.37135651,
       53839.83670062, 53832.79442768, 53831.29320439, 53831.49970346,
       53831.23224971, 53833.37193081, 53835.0740862 , 53835.36355996,
       53950.4551174 , 53976.95414898, 53976.95414898, 53976.95445791,
       53977.40537691, 53976.95445791, 53976.95445791, 53976.95414898,
       53833.37193081, 53844.37135651, 53745.98707563])

In [20]:
len(y_pred)

375

In [21]:
testresult=pd.DataFrame({"id": ids, "feature_2":y_pred})
testresult

      id     feature_2
0    564  53930.979079
1    565  53930.979079
2    566  53930.979079
3    567  53936.366782
4    568  53936.366782
..   ...           ...
370  934  53976.954458
371  935  53976.954149
372  936  53833.371931
373  937  53844.371357
374  938  53745.987076

[375 rows x 2 columns]

In [22]:
testresult.to_csv("solution.csv", index=False) #stored in the same directory as the python notebook